### ISSUE TITLE
MELD-Datafolder

### ISSUE THREAD

**Issue by LuPo1995** [jbdel/modulated_fusion_transformer#1]
Hi,

first of all, great work! 
I have a problem, I would like to use the MELD pretrained Network, but the Dropbox link does not include the MELD folder. Is it possible to get access to the MELD folder to get similar results ? 
Thanks

**Comment by jbdel** [comment]
Hello,

I have added MELD in the data.zip.
You should be able to replicate the meld results using the pretrained checkpoints. 
Dont hesitate to contact me otherwise.
